#!/bin/bash

sudo scp /export/rootfs/root/c1.log data/c1.log
sudo scp /export/rootfs/root/c2.log data/c2.log
sudo scp /export/rootfs/root/c3.log data/c3.log

sudo scp /export/rootfs/root/n1.log data/n1.log
sudo scp /export/rootfs/root/n2.log data/n2.log
sudo scp /export/rootfs/root/n3.log data/n3.log

sudo scp /export/rootfs/root/l1.log data/l1.log
sudo scp /export/rootfs/root/l2.log data/l2.log
sudo scp /export/rootfs/root/l3.log data/l3.log

sudo scp /export/rootfs/root/l1n.log data/l1n.log
sudo scp /export/rootfs/root/l2n.log data/l2n.log
sudo scp /export/rootfs/root/l3n.log data/l3n.log

sudo scp /export/rootfs/root/u1.log data/u1.log
sudo scp /export/rootfs/root/u2.log data/u2.log
sudo scp /export/rootfs/root/u3.log data/u3.log

sudo scp /export/rootfs/root/u1n.log data/u1n.log
sudo scp /export/rootfs/root/u2n.log data/u2n.log
sudo scp /export/rootfs/root/u3n.log data/u3n.log

