/* -*- C++ -*- */
/* Generated by /home/asymingt/Workspace/thirdparty/linuxptp/thirdparty/OpenDDS/bin/opendds_idl version 3.7 (ACE version 6.2a_p7) running on input file /home/asymingt/Workspace/thirdparty/linuxptp/src/messages/Timeline.idl */
#ifndef OPENDDS_IDL_GENERATED_TIMELINETYPESUPPORTIMPL_H_NDDA1C
#define OPENDDS_IDL_GENERATED_TIMELINETYPESUPPORTIMPL_H_NDDA1C
#include "TimelineC.h"
#include "dds/DCPS/Definitions.h"
#include "dds/DCPS/Serializer.h"


/* Begin MODULE: CORBA */


/* End MODULE: CORBA */


/* Begin STRUCT: Timeline */

namespace OpenDDS { namespace DCPS {

void gen_find_size(const Timeline& stru, size_t& size, size_t& padding);

bool operator<<(Serializer& strm, const Timeline& stru);

bool operator>>(Serializer& strm, Timeline& stru);

}  }

#ifndef OPENDDS_NO_CONTENT_SUBSCRIPTION_PROFILE
namespace OpenDDS { namespace DCPS {

class MetaStruct;

template<typename T>
const MetaStruct& getMetaStruct();

template<>
const MetaStruct& getMetaStruct<Timeline>();
void gen_skip_over(Serializer& ser, Timeline*);

}  }

#endif

/* End STRUCT: Timeline */
#endif /* OPENDDS_IDL_GENERATED_TIMELINETYPESUPPORTIMPL_H_NDDA1C */
